name: Docker
on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: "Build Frontend"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          file: Dockerfile
          tags: |
            ghcr.io/csesoc/tech-spire-2022:${{ github.sha }}
            ghcr.io/csesoc/tech-spire-2022:latest
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    name: Deploy (CD)
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: csesoc/deployment
          token: ${{ secrets.GH_TOKEN }}
      - name: Install yq - portable yaml processor
        uses: mikefarah/yq@v4.27.2
      - name: Update deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "CSESoc CD"
          git config user.email "technical@csesoc.org.au"
          git checkout -b update/tech-spire-2022/${{ github.sha }}
          yq -i '.items[0].spec.template.spec.containers[0].image = "ghcr.io/csesoc/tech-spire-2022:${{ github.sha }}"' apps/projects/tech-spire-2022/deploy.yml
          git add .
          git commit -m "feat(tech-spire-2022): update images"
          git push -u origin update/tech-spire-2022/${{ github.sha }}
          gh pr create --title "feat(tech-spire-2022): update image" --body "Updates the images for the tech-spire-2022 deployment to commit csesoc/tech-spire-2022@${{ github.sha }}." > URL
          gh pr merge $(cat URL) --squash -d
