name: Docker
on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: "Build Frontend"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          file: Dockerfile
          tags: |
            ghcr.io/csesoc/tech-spire-2022:${{ github.sha }}
            ghcr.io/csesoc/tech-spire-2022:latest
          labels: ${{ steps.meta.outputs.labels }}
